#!/bin/zsh
#
# configuration for Amazon Web Services
#

local creds_dir=$HOME/.ssh/certs/zeevex

export EC2_PRIVATE_KEY=$creds_dir/aws-sudish-cert-key-pkcs8.pem
export EC2_CERT=$creds_dir/aws-sudish-cert.pem

# defining the AWS_CREDENTIAL_FILE causes rds tools to blow up
#export AWS_CREDENTIAL_FILE=$creds_dir/aws-sudish-iam-credentials-master

export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.5.2.4/jars"
export AWS_RDS_HOME="/usr/local/Cellar/rds-command-line-tools/1.3.003/jars"
export EC2_AMITOOL_HOME="/usr/local/Cellar/ec2-ami-tools/1.3-45758/jars"
export AWS_IAM_HOME="/usr/local/Cellar/aws-iam-tools/HEAD/jars"
export AWS_CLOUDFORMATION_HOME="/usr/local/Cellar/aws-cfn-tools/1.0.9/jars"
