#!/bin/zsh
#
# Functions to ease building Emacs from the repo
#

EMACS_PREFIX=/opt/sj/emacs
EMACS_CC_FLAGS=(CC=gcc-4.2 CXX=g++-4.2 CFLAGS="-pipe -Wall -fast \
	-arch x86_64 -m64 -march=core2 -mtune=core2 -mmmx -msse4.1")
EMACS_CONF_FLAGS=(--verbose --with-x --with-sound --with-imagemagick \
    --without-pop --prefix=$EMACS_PREFIX)

sj_emacsupdate () {
    git tag -f sj-pull >/dev/null 2>&1 # last HEAD, aka HEAD@{1}
    git pull \
	&& git rebase origin
}

sj_emacsconfigure () {
    print -z $EMACS_CC_FLAGS `sj_configure` $EMACS_CONF_FLAGS
}

sj_emacsbuild () {
    local build_dir
    build_dir=sj-build.$$

    git clean -qxfd
    mkdir $build_dir || { echo "couldn't mkdir $build_dir: $!"; return 1 }
    cd $build_dir

    env "$EMACS_CC_FLAGS[@]" `sj_configure` "$EMACS_CONF_FLAGS[@]" \
	&& nice -n 20 make -j2 \
	&& git tag -f sj-build
}

sj_emacsinstall () {
    local old bak
    
    old=$EMACS_PREFIX
    bak=/tmp/emacs-$(date -r $old '+%s')
    
    if [[ -x $old ]]; then
	mv $old $bak
    fi

    nice -n 20 make install \
	&& git tag -f sj-install \
	&& cd .. \
	&& git clean -qxfd
}
