#!/bin/zsh
#
# Use keychain to start and manage ssh-agent
#

sj_setup_ssh_agent() {
    local kcfiles file keyhost
    keyhost=sudish		# use a fixed hostname, no nfs here
    
    if [[ `whoami` == 'sj' || `whoami` == 'sudish' ]]; then
	kcfiles=()
	for file in `cat ~/.ssh/agent-keyfiles 2>/dev/null`; do
            keyfile=${file}_rsa
	    [[ -r ~/.ssh/$keyfile ]] && kcfiles+="$keyfile"
	done
	if [[ -n $kcfiles ]] ; then
	    keychain --agents ssh --host "$keyhost" -q "$kcfiles[@]"
	    source "$HOME/.keychain/${keyhost}-sh"
	else
	    fgrep ForwardAgent ~/.ssh/config >&| /dev/null || \
		echo "No keyfiles for ssh_agent or ForwardAgent!"
	fi
    fi
}

sj_setup_ssh_agent
