#!/bin/zsh
#
# Functions to ease building Emacs from the repo
#

EMACS_CC_FLAGS=(CC=gcc-4.2 CXX=g++-4.2 CFLAGS="-O2 -pipe -Wall")
EMACS_CONF_FLAGS=(--verbose --with-ns \
    --without-pop --without-x --with-x-toolkit=no)

sj_emacsupdate () {
    git tag -f sj-pull >/dev/null 2>&1 # last HEAD, aka HEAD@{1}
    git pull \
	&& git rebase origin
}

sj_emacsconfigure () {
    print -z $EMACS_CC_FLAGS `sj_configure` $EMACS_CONF_FLAGS
}

sj_emacsbuild () {
    local build_dir
    build_dir=sj-build.$$

    git clean -qxfd	    # [[ -d $build_dir ]] && rm -rf $build_dir
    mkdir $build_dir || { echo "couldn't mkdir $build_dir: $!"; return 1 }
    cd $build_dir

    env "$EMACS_CC_FLAGS[@]" `sj_configure` "$EMACS_CONF_FLAGS[@]" \
	&& nice -n 20 make -j3 \
	&& nice -n 20 make install \
	&& git tag -f sj-build
}

sj_emacsinstall () {
    local old new bak
    
    old=/Applications/Emacs.app
    new=nextstep/Emacs.app
    bak=/tmp/Emacs-$(date -r $old '+%s').app
    
    if [[ -x $new ]]; then
	mv $old $bak \
	    && mv $new $old \
	    && git tag -f sj-install
    else
	echo "$new doesn't exist"
    fi
}
