#!/bin/zsh

# Run various tmux commands from a standard location, starting a new
# tmux session if run outside one.
function tc() {
    local conf_dir="$HOME/.tmux_configs"
    local conf_file="$conf_dir/$1"

    if [[ -z $1 || ! -r $conf_file ]] ; then
	[[ -z $1 ]] && echo "Usage: $0 <configuration>"
	[[ ! -r $conf_file ]] && echo "No such configuration: $conf_file"
	return 1
    fi
    
    if [[ -z $TMUX ]] ; then
	# We're not running inside a tmux session, so start one and
	# then run the config inside it.  No window is created by
	# default when new-session is asked to exec commands, so we
	# explicitly ask for one here.
	tmux new-session "tmux new-window; source $conf_file" 
    else
	source $conf_file
    fi
}
