#!/bin/zsh

# Run various tmux commands from a standard location, starting a new
# tmux session if run outside one.
function tc() {
    local conf_dir="$HOME/.tmux_configs"
    local conf_file="$conf_dir/$1"

    if [[ -z $1 || ! -r $conf_file ]] ; then
        [[ -z $1 ]] && echo "Usage: $0 <configuration>"
        [[ ! -r $conf_file ]] && echo "No such configuration: $conf_file"
        return 1
    fi
    
    if [[ -z $TMUX ]] ; then
	# Pre tmux-1.2, Nicholas Marriott says: "new-session without
	# -d implies attach and that stops further command
	# processing."  So we source using a shell cmd inside tmux:
	# tmux new-session "tmux new-window \\; source $conf_file"
	#
	# new-session does the right thing in tmux-1.2 and later:
        tmux new-session \; source $conf_file
    else
        tmux source $conf_file
    fi
}
