# -*- ruby -*-

source :gemcutter

gem 'rake'
gem 'htty'
gem 'git-up'
gem 'git_tracker'
gem 'heroku'
gem 'foreman'
gem 'powify'
gem 'pry'
gem 'pry-doc'
gem 'rcodetools'

# os x
gem 'rb-fsevent'
gem 'growl'

# old version of vagrant else we use a really old version of ffi
# that doesn't compile with 1.9.3
#gem 'vagrant',  '~> 0.9.7'
