# -*- ruby -*-

source 'https://rubygems.org'

gem 'rake'
gem 'htty'
gem 'git-up'
gem 'git_tracker'
gem 'heroku'
gem 'foreman'
gem 'localtunnel'
gem 'powify'
gem 'pry'
gem 'pry-doc'
gem 'rcodetools'
gem 'tunnels'

# os x
gem 'rb-fsevent'
gem 'growl'
